/// <reference path="../../../global.d.ts" />
export default class Window_Base extends Window {
    _opening: boolean;
    _closing: boolean;
    _dimmerSprite: typeof Sprite;
    constructor(...args: any[]);
    initialize(rect: any): void;
    destroy(options: any): void;
    checkRectObject(rect: any): void;
    lineHeight(): number;
    itemWidth(): number;
    itemHeight(): number;
    itemPadding(): number;
    baseTextRect(): import("../..").Rectangle;
    loadWindowskin(): void;
    updatePadding(): void;
    updateBackOpacity(): void;
    fittingHeight(numLines: any): number;
    updateTone(): void;
    createContents(): void;
    destroyContents(): void;
    contentsWidth(): number;
    contentsHeight(): number;
    resetFontSettings(): void;
    resetTextColor(): void;
    update(): void;
    updateOpen(): void;
    updateClose(): void;
    open(): void;
    close(): void;
    isOpening(): boolean;
    isClosing(): boolean;
    show(): void;
    hide(): void;
    activate(): void;
    deactivate(): void;
    systemColor(): any;
    translucentOpacity(): number;
    changeTextColor(color: any): void;
    changeOutlineColor(color: any): void;
    changePaintOpacity(enabled: any): void;
    drawRect(x: any, y: any, width: any, height: any): void;
    drawText(text: any, x: any, y: any, maxWidth: any, align: any): void;
    textWidth(text: any): any;
    drawTextEx(text: any, x: any, y: any, width: any): any;
    textSizeEx(text: any): {
        width: any;
        height: any;
    };
    createTextState(text: any, x: any, y: any, width: any): {};
    processAllText(textState: any): void;
    flushTextState(textState: any): void;
    createTextBuffer(rtl: any): "" | "‫";
    convertEscapeCharacters(text: any): any;
    actorName(n: any): any;
    partyMemberName(n: any): any;
    processCharacter(textState: any): void;
    processControlCharacter(textState: any, c: any): void;
    processNewLine(textState: any): void;
    obtainEscapeCode(textState: any): string;
    obtainEscapeParam(textState: any): number | "";
    processEscapeCharacter(code: any, textState: any): void;
    processColorChange(colorIndex: any): void;
    processDrawIcon(iconIndex: any, textState: any): void;
    makeFontBigger(): void;
    makeFontSmaller(): void;
    calcTextHeight(textState: any): any;
    maxFontSizeInLine(line: any): any;
    drawIcon(iconIndex: any, x: any, y: any): void;
    drawFace(faceName: any, faceIndex: any, x: any, y: any, width?: number, height?: number): void;
    drawCharacter(characterName: any, characterIndex: any, x: any, y: any): void;
    drawItemName(item: any, x: any, y: any, width: any): void;
    drawCurrencyValue(value: any, unit: any, x: any, y: any, width: any): void;
    setBackgroundType(type: any): void;
    showBackgroundDimmer(): void;
    createDimmerSprite(): void;
    hideBackgroundDimmer(): void;
    updateBackgroundDimmer(): void;
    refreshDimmerBitmap(): void;
    playCursorSound(): void;
    playOkSound(): void;
    playBuzzerSound(): void;
}
