/// <reference path="../../../global.d.ts" />
export default class Scene_Battle extends Scene_Message {
    _spriteset: typeof Spriteset_Battle;
    _logWindow: typeof Window_BattleLog;
    _statusWindow: unknown;
    _partyCommandWindow: unknown;
    _actorCommandWindow: unknown;
    _helpWindow: typeof Window_Help;
    _skillWindow: typeof Window_BattleSkill;
    _itemWindow: typeof Window_BattleItem;
    _actorWindow: typeof Window_BattleActor;
    _enemyWindow: typeof Window_BattleEnemy;
    _cancelButton: typeof Sprite_Button;
    constructor(...args: any[]);
    initialize(): void;
    create(): void;
    start(): void;
    update(): void;
    updateVisibility(): void;
    updateBattleProcess(): void;
    isTimeActive(): boolean;
    isAnyInputWindowActive(): any;
    changeInputWindow(): void;
    stop(): void;
    terminate(): void;
    shouldAutosave(): boolean;
    needsSlowFadeOut(): boolean;
    updateLogWindowVisibility(): void;
    updateStatusWindowVisibility(): void;
    shouldOpenStatusWindow(): boolean;
    updateStatusWindowPosition(): void;
    statusWindowX(): number;
    updateInputWindowVisibility(): void;
    needsInputWindowChange(): boolean;
    updateCancelButton(): void;
    createDisplayObjects(): void;
    createSpriteset(): void;
    createAllWindows(): void;
    createLogWindow(): void;
    logWindowRect(): import("../..").Rectangle;
    createStatusWindow(): void;
    statusWindowRect(): import("../..").Rectangle;
    createPartyCommandWindow(): void;
    partyCommandWindowRect(): import("../..").Rectangle;
    createActorCommandWindow(): void;
    actorCommandWindowRect(): import("../..").Rectangle;
    createHelpWindow(): void;
    helpWindowRect(): import("../..").Rectangle;
    createSkillWindow(): void;
    skillWindowRect(): import("../..").Rectangle;
    createItemWindow(): void;
    itemWindowRect(): import("../..").Rectangle;
    createActorWindow(): void;
    actorWindowRect(): import("../..").Rectangle;
    createEnemyWindow(): void;
    enemyWindowRect(): import("../..").Rectangle;
    helpAreaTop(): number;
    helpAreaBottom(): number;
    helpAreaHeight(): number;
    buttonAreaTop(): number;
    windowAreaHeight(): number;
    createButtons(): void;
    createCancelButton(): void;
    closeCommandWindows(): void;
    hideSubInputWindows(): void;
    startPartyCommandSelection(): void;
    commandFight(): void;
    commandEscape(): void;
    startActorCommandSelection(): void;
    commandAttack(): void;
    commandSkill(): void;
    commandGuard(): void;
    commandItem(): void;
    commandCancel(): void;
    selectNextCommand(): void;
    selectPreviousCommand(): void;
    startActorSelection(): void;
    onActorOk(): void;
    onActorCancel(): void;
    startEnemySelection(): void;
    onEnemyOk(): void;
    onEnemyCancel(): void;
    onSkillOk(): void;
    onSkillCancel(): void;
    onItemOk(): void;
    onItemCancel(): void;
    onSelectAction(): void;
    endCommandSelection(): void;
}
