/// <reference path="../../../global.d.ts" />
export default class Scene_Map extends Scene_Message {
    _waitCount: number;
    _encounterEffectDuration: unknown;
    _mapLoaded: boolean;
    _touchCount: number;
    _menuEnabled: unknown;
    _transfer: unknown;
    _lastMapWasNull: boolean;
    _spriteset: typeof Spriteset_Map;
    _mapNameWindow: typeof Window_MapName;
    _menuButton: typeof Sprite_Button;
    constructor(...args: any[]);
    initialize(): void;
    create(): void;
    isReady(): any;
    onMapLoaded(): void;
    onTransfer(): void;
    start(): void;
    onTransferEnd(): void;
    shouldAutosave(): boolean;
    update(): void;
    updateMainMultiply(): void;
    updateMain(): void;
    isPlayerActive(): boolean;
    isFastForward(): boolean;
    stop(): void;
    isBusy(): any;
    terminate(): void;
    needsFadeIn(): boolean;
    needsSlowFadeOut(): boolean;
    updateWaitCount(): boolean;
    updateDestination(): void;
    updateMenuButton(): void;
    hideMenuButton(): void;
    updateMapNameWindow(): void;
    isMenuEnabled(): boolean;
    isMapTouchOk(): any;
    processMapTouch(): void;
    isAnyButtonPressed(): any;
    onMapTouch(): void;
    isSceneChangeOk(): boolean;
    updateScene(): void;
    createDisplayObjects(): void;
    createSpriteset(): void;
    createAllWindows(): void;
    createMapNameWindow(): void;
    mapNameWindowRect(): import("../..").Rectangle;
    createButtons(): void;
    createMenuButton(): void;
    updateTransferPlayer(): void;
    updateEncounter(): void;
    updateCallMenu(): void;
    isMenuCalled(): any;
    callMenu(): void;
    updateCallDebug(): void;
    isDebugCalled(): any;
    fadeInForTransfer(): void;
    fadeOutForTransfer(): void;
    launchBattle(): void;
    stopAudioOnBattleStart(): void;
    startEncounterEffect(): void;
    updateEncounterEffect(): void;
    snapForBattleBackground(): void;
    startFlashForEncounter(duration: any): void;
    encounterEffectSpeed(): number;
}
