/// <reference path="../../../global.d.ts" />
export default class Scene_Base extends Stage {
    _started: boolean;
    _active: boolean;
    _fadeSign: number;
    _fadeDuration: number;
    _fadeWhite: unknown;
    _fadeOpacity: number;
    _windowLayer: typeof WindowLayer;
    _colorFilter: typeof ColorFilter;
    constructor(...args: any[]);
    initialize(): void;
    create(): void;
    isActive(): boolean;
    isReady(): boolean;
    start(): void;
    update(): void;
    stop(): void;
    isStarted(): boolean;
    isBusy(): boolean;
    isFading(): boolean;
    terminate(): void;
    createWindowLayer(): void;
    addWindow(window: any): void;
    startFadeIn(duration: any, white: any): void;
    startFadeOut(duration: any, white: any): void;
    createColorFilter(): void;
    updateColorFilter(): void;
    updateFade(): void;
    updateChildren(): void;
    popScene(): void;
    checkGameover(): void;
    fadeOutAll(): void;
    fadeSpeed(): number;
    slowFadeSpeed(): number;
    scaleSprite(sprite: any): void;
    centerSprite(sprite: any): void;
    isBottomHelpMode(): boolean;
    isBottomButtonMode(): boolean;
    isRightInputMode(): boolean;
    mainCommandWidth(): number;
    buttonAreaTop(): number;
    buttonAreaBottom(): number;
    buttonAreaHeight(): number;
    buttonY(): number;
    calcWindowHeight(numLines: any, selectable: any): number;
    requestAutosave(): void;
    isAutosaveEnabled(): any;
    executeAutosave(): void;
    onAutosaveSuccess(): void;
    onAutosaveFailure(): void;
}
