/// <reference path="../../../global.d.ts" />
export default class Game_Screen {
    _brightness: number;
    _fadeOutDuration: unknown;
    _fadeInDuration: unknown;
    _tone: unknown;
    _toneTarget: unknown;
    _toneDuration: unknown;
    _flashColor: unknown;
    _flashDuration: unknown;
    _shakePower: unknown;
    _shakeSpeed: unknown;
    _shakeDuration: unknown;
    _shakeDirection: number;
    _shake: number;
    _zoomX: unknown;
    _zoomY: unknown;
    _zoomScale: number;
    _zoomScaleTarget: unknown;
    _zoomDuration: unknown;
    _weatherType: unknown;
    _weatherPower: number;
    _weatherPowerTarget: unknown;
    _weatherDuration: unknown;
    _pictures: unknown;
    constructor(...args: any[]);
    initialize(): void;
    clear(): void;
    onBattleStart(): void;
    brightness(): number;
    tone(): unknown;
    flashColor(): unknown;
    shake(): number;
    zoomX(): unknown;
    zoomY(): unknown;
    zoomScale(): number;
    weatherType(): unknown;
    weatherPower(): number;
    picture(pictureId: any): any;
    realPictureId(pictureId: any): any;
    clearFade(): void;
    clearTone(): void;
    clearFlash(): void;
    clearShake(): void;
    clearZoom(): void;
    clearWeather(): void;
    clearPictures(): void;
    eraseBattlePictures(): void;
    maxPictures(): number;
    startFadeOut(duration: any): void;
    startFadeIn(duration: any): void;
    startTint(tone: any, duration: any): void;
    startFlash(color: any, duration: any): void;
    startShake(power: any, speed: any, duration: any): void;
    startZoom(x: any, y: any, scale: any, duration: any): void;
    setZoom(x: any, y: any, scale: any): void;
    changeWeather(type: any, power: any, duration: any): void;
    update(): void;
    updateFadeOut(): void;
    updateFadeIn(): void;
    updateTone(): void;
    updateFlash(): void;
    updateShake(): void;
    updateZoom(): void;
    updateWeather(): void;
    updatePictures(): void;
    startFlashForDamage(): void;
    showPicture(pictureId: any, name: any, origin: any, x: any, y: any, scaleX: any, scaleY: any, opacity: any, blendMode: any): void;
    movePicture(pictureId: any, origin: any, x: any, y: any, scaleX: any, scaleY: any, opacity: any, blendMode: any, duration: any, easingType: any): void;
    rotatePicture(pictureId: any, speed: any): void;
    tintPicture(pictureId: any, tone: any, duration: any): void;
    erasePicture(pictureId: any): void;
}
