/// <reference path="../../../global.d.ts" />
export default class Game_CharacterBase {
    _x: unknown;
    _y: unknown;
    _realX: unknown;
    _realY: unknown;
    _moveSpeed: unknown;
    _moveFrequency: unknown;
    _opacity: unknown;
    _blendMode: unknown;
    _direction: unknown;
    _pattern: unknown;
    _priorityType: unknown;
    _tileId: unknown;
    _characterName: unknown;
    _characterIndex: unknown;
    _isObjectCharacter: boolean;
    _walkAnime: unknown;
    _stepAnime: unknown;
    _directionFix: unknown;
    _through: unknown;
    _transparent: unknown;
    _bushDepth: unknown;
    _animationId: number;
    _balloonId: number;
    _animationPlaying: boolean;
    _balloonPlaying: boolean;
    _animationCount: number;
    _stopCount: number;
    _jumpCount: number;
    _jumpPeak: number;
    _movementSuccess: unknown;
    constructor(...args: any[]);
    initialize(): void;
    initMembers(): void;
    pos(x: any, y: any): boolean;
    posNt(x: any, y: any): boolean;
    moveSpeed(): unknown;
    setMoveSpeed(moveSpeed: any): void;
    moveFrequency(): unknown;
    setMoveFrequency(moveFrequency: any): void;
    opacity(): unknown;
    setOpacity(opacity: any): void;
    blendMode(): unknown;
    setBlendMode(blendMode: any): void;
    isNormalPriority(): boolean;
    setPriorityType(priorityType: any): void;
    isMoving(): boolean;
    isJumping(): boolean;
    jumpHeight(): number;
    isStopping(): boolean;
    checkStop(threshold: any): boolean;
    resetStopCount(): void;
    realMoveSpeed(): any;
    distancePerFrame(): number;
    isDashing(): boolean;
    isDebugThrough(): boolean;
    straighten(): void;
    reverseDir(d: any): number;
    canPass(x: any, y: any, d: any): boolean;
    canPassDiagonally(x: any, y: any, horz: any, vert: any): boolean;
    isMapPassable(x: any, y: any, d: any): any;
    isCollidedWithCharacters(x: any, y: any): any;
    isCollidedWithEvents(x: any, y: any): any;
    isCollidedWithVehicles(x: any, y: any): any;
    setPosition(x: any, y: any): void;
    copyPosition(character: any): void;
    locate(x: any, y: any): void;
    direction(): unknown;
    setDirection(d: any): void;
    isTile(): boolean;
    isObjectCharacter(): boolean;
    shiftY(): 0 | 6;
    scrolledX(): any;
    scrolledY(): any;
    screenX(): number;
    screenY(): number;
    screenZ(): number;
    isNearTheScreen(): boolean;
    update(): void;
    updateStop(): void;
    updateJump(): void;
    updateMove(): void;
    updateAnimation(): void;
    animationWait(): number;
    updateAnimationCount(): void;
    updatePattern(): void;
    maxPattern(): number;
    pattern(): unknown;
    setPattern(pattern: any): void;
    isOriginalPattern(): boolean;
    resetPattern(): void;
    refreshBushDepth(): void;
    isOnLadder(): any;
    isOnBush(): any;
    terrainTag(): any;
    regionId(): any;
    increaseSteps(): void;
    tileId(): unknown;
    characterName(): unknown;
    characterIndex(): unknown;
    setImage(characterName: any, characterIndex: any): void;
    setTileImage(tileId: any): void;
    checkEventTriggerTouchFront(d: any): void;
    checkEventTriggerTouch(): boolean;
    isMovementSucceeded(): unknown;
    setMovementSuccess(success: any): void;
    moveStraight(d: any): void;
    moveDiagonally(horz: any, vert: any): void;
    jump(xPlus: any, yPlus: any): void;
    hasWalkAnime(): unknown;
    setWalkAnime(walkAnime: any): void;
    hasStepAnime(): unknown;
    setStepAnime(stepAnime: any): void;
    isDirectionFixed(): unknown;
    setDirectionFix(directionFix: any): void;
    isThrough(): unknown;
    setThrough(through: any): void;
    isTransparent(): unknown;
    bushDepth(): unknown;
    setTransparent(transparent: any): void;
    startAnimation(): void;
    startBalloon(): void;
    isAnimationPlaying(): boolean;
    isBalloonPlaying(): boolean;
    endAnimation(): void;
    endBalloon(): void;
}
