/// <reference path="../../../global.d.ts" />
export default class Game_Message {
    _texts: [];
    _choices: unknown;
    _speakerName: unknown | string;
    _faceName: unknown;
    _faceIndex: unknown;
    _background: unknown;
    _positionType: unknown;
    _choiceDefaultType: unknown;
    _choiceCancelType: unknown;
    _choiceBackground: unknown;
    _choicePositionType: unknown;
    _numInputVariableId: unknown;
    _numInputMaxDigits: unknown;
    _itemChoiceVariableId: unknown;
    _itemChoiceItypeId: unknown;
    _scrollMode: boolean;
    _scrollSpeed: unknown;
    _scrollNoFast: unknown;
    _choiceCallback: unknown;
    constructor(...args: any[]);
    initialize(): void;
    clear(): void;
    choices(): unknown;
    speakerName(): unknown;
    faceName(): unknown;
    faceIndex(): unknown;
    background(): unknown;
    positionType(): unknown;
    choiceDefaultType(): unknown;
    choiceCancelType(): unknown;
    choiceBackground(): unknown;
    choicePositionType(): unknown;
    numInputVariableId(): unknown;
    numInputMaxDigits(): unknown;
    itemChoiceVariableId(): unknown;
    itemChoiceItypeId(): unknown;
    scrollMode(): boolean;
    scrollSpeed(): unknown;
    scrollNoFast(): unknown;
    add(text: any): void;
    setSpeakerName(speakerName: any): void;
    setFaceImage(faceName: any, faceIndex: any): void;
    setBackground(background: any): void;
    setPositionType(positionType: any): void;
    setChoices(choices: any, defaultType: any, cancelType: any): void;
    setChoiceBackground(background: any): void;
    setChoicePositionType(positionType: any): void;
    setNumberInput(variableId: any, maxDigits: any): void;
    setItemChoice(variableId: any, itemType: any): void;
    setScroll(speed: any, noFast: any): void;
    setChoiceCallback(callback: any): void;
    onChoice(n: any): void;
    hasText(): boolean;
    isChoice(): boolean;
    isNumberInput(): boolean;
    isItemChoice(): boolean;
    isBusy(): boolean;
    newPage(): void;
    allText(): string;
    isRTL(): boolean;
}
