import { RPG } from "@niokasgami/rpg-maker-mz-typescript/lib/RPG";
export type Actors = RPG.DataActor[];
export type Animations = RPG.DataAnimation[];
export type Armors = RPG.DataArmor[];
export type Classes = RPG.DataClass[];
export type CommonEvents = RPG.DataCommonEvent[];
export type Enemies = RPG.DataEnemy[];
export type Items = RPG.DataItem[];
export type Map = RPG.DataMap;
export type MapInfos = RPG.DataMapInfo[];
export type Skills = RPG.DataSkill[];
export type States = RPG.DataState[];
export type System = RPG.DataSystem;
export type Tilesets = RPG.DataTileset[];
export type Troops = RPG.DataTroop[];
export type Weapons = RPG.DataWeapon[];
